### ISSUE TITLE
タイピングを間違えた後の動作が分かりにくいです。

### ISSUE THREAD

**Issue by CatNigth0211** [macinjoke/study-typer-frontend#3]
初めまして。こんにちは。
Study Typerの入力をミスした後にどうするのか。が、わかりづらいです。正解は青、ミスタイピングは黄色まではわかるのですが、その後の修正をして次に進む挙動が分かりづらいです。
入力した文字が黄色になった後にユーザーはどのような修正作業をして次に進めばいいのかの説明を追加したほうがわかりやすいと思います。

余談ですが、私がStudy Typerで文字入力をミスした後の動作は、
①エンターを押して次に進むか試す。
②動かないのでブラウザをとじる
③他の文字を適当に入力する 

の３つの挙動を主にしていました。正解のBack Space を押下に辿り着いたのは色々弄った後でした。

**Comment by macinjoke** [comment]
フィードバックありがとうございます！
確かにどこかに説明を書いておく必要がありそうですね。
今度直します。

**Comment by macinjoke** [comment]
修正しました。
ヘッダーに BackSpace キーについて書いておきました。
